-- =====================================================================================================================
-- 01-schema.sql · TABLAS, COLUMNAS, TIPOS, DEFAULTS, IDENTITY Y SECUENCIAS                                                     [SOLO STAGING · NO EJECUTAR EN PRODUCCIÓN]
-- Generado por scripts/staging/generar-esquema.mjs desde RESULTADO-ESQUEMA-PRODUCCION.json (2026-09-19T15:38:18Z, PostgreSQL 17.6 on aarch64-unknown-linux-gnu).
-- NO EDITAR A MANO: se regenera. Reproduce producción TAL CUAL (incluidas policies/permisos abiertos): NO corrige vulnerabilidades.
-- No contiene datos. No toca tablas backup_*. Se ejecuta completo, en una sola corrida, dentro de una transacción.
-- Orden interno: extensiones → secuencias → tablas (10) → propiedad de secuencias.
-- El RLS se habilita en 05-rls-policies.sql (si el proyecto trae el event trigger de RLS automático, ya vendrá habilitado: es idempotente).
-- =====================================================================================================================

begin;

-- Los nombres sin esquema (usuarios, cargas, *_seq, set_updated_at) se resuelven en public, sin depender del search_path del rol.
set local search_path to public, extensions;

-- ── GUARDA ANTI-PRODUCCIÓN ─────────────────────────────────────────────────────────────────────────
-- Producción tiene las tablas backup_*_20260614; un proyecto de staging NO debe tenerlas. Si existen, esto NO es staging.
do $guarda$
begin
  if to_regclass('public.backup_usuarios_20260614') is not null
     or to_regclass('public.backup_cargas_20260614') is not null then
    raise exception 'ABORTADO (01-schema): existen tablas backup_*_20260614 => esto parece PRODUCCIÓN. Estos archivos son SOLO para STAGING.';
  end if;
end
$guarda$;

do $existe$
begin
  if to_regclass('public.usuarios') is not null or to_regclass('public.cargas') is not null then
    raise exception 'ABORTADO (01-schema): public.usuarios/public.cargas ya existen. Usar rollback-staging.sql antes de reintentar.';
  end if;
end
$existe$;

-- Extensiones que producción tiene instaladas (ninguna es requerida por el esquema: gen_random_uuid() es nativo de PG13+).
create extension if not exists pgcrypto  with schema extensions;
create extension if not exists "uuid-ossp" with schema extensions;

-- Secuencias estilo serial (las columnas tienen DEFAULT nextval(...)). cargas.id es IDENTITY y crea la suya sola.
create sequence public.consentimientos_legales_id_seq as bigint increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public.paradas_viaje_id_seq as bigint increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public.vehiculos_id_seq as bigint increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;
create sequence public.viaje_evidencias_id_seq as bigint increment by 1 minvalue 1 maxvalue 9223372036854775807 start with 1 cache 1 no cycle;

-- billetera_chofer
create table public.billetera_chofer (
  id                          uuid not null default gen_random_uuid(),
  chofer_id                   text,
  monto                       numeric,
  created_at                  timestamp without time zone default now(),
  viaje_id                    text
);

-- cargas
create table public.cargas (
  id                          bigint generated by default as identity,
  created_at                  timestamp with time zone not null default now(),
  origen                      text,
  destino                     text,
  peso                        text,
  precio                      text,
  vehiculo                    text,
  estado                      text,
  detalles                    text,
  cliente_id                  text,
  chofer_id                   text,
  tipo_carga                  text,
  tracking                    boolean default false,
  precio_base                 numeric,
  precio_cliente              numeric,
  pago_chofer                 numeric,
  comision_plataforma         numeric,
  km_estimados                numeric,
  litros_por_km               numeric,
  lat                         double precision,
  lng                         double precision,
  velocidad                   double precision,
  gps_actualizado             timestamp without time zone,
  hora_aceptacion             timestamp with time zone,
  hora_inicio                 timestamp with time zone,
  hora_finalizacion           timestamp with time zone,
  velocidad_kmh               numeric default 0,
  ultima_senal_at             timestamp with time zone,
  categoria_legal             text,
  tipo_vehiculo               text,
  tipo_carroceria             text,
  oculto_cliente              boolean default false,
  oculto_chofer               boolean default false,
  auto_oculto_at              timestamp with time zone,
  pagado_cliente              boolean default false,
  mp_payment_id               text,
  mp_preference_id            text,
  mp_status                   text,
  mp_monto                    numeric,
  pago_estado                 text default 'pendiente_pago'::text
);

-- consentimientos_legales
create table public.consentimientos_legales (
  id                          bigint not null default nextval('consentimientos_legales_id_seq'::regclass),
  usuario_id                  uuid not null,
  tipo_documento              text not null,
  version_documento           text not null,
  fecha_hora                  timestamp with time zone not null default now(),
  ip_address                  text,
  user_agent                  text,
  metodo                      text not null default 'checkbox_registro'::text
);

-- documentacion_chofer
create table public.documentacion_chofer (
  id                          uuid not null default gen_random_uuid(),
  chofer_id                   uuid not null,
  tipo                        text not null,
  url                         text not null,
  created_at                  timestamp with time zone default now()
);

-- mensajes_viaje
create table public.mensajes_viaje (
  id                          uuid not null default gen_random_uuid(),
  viaje_id                    bigint not null,
  remitente_id                uuid not null,
  remitente_rol               text not null,
  remitente_nombre            text not null,
  mensaje                     text not null,
  leido                       boolean default false,
  created_at                  timestamp with time zone default now(),
  tipo_chat                   text default 'viaje'::text
);

-- paradas_viaje
create table public.paradas_viaje (
  id                          bigint not null default nextval('paradas_viaje_id_seq'::regclass),
  carga_id                    bigint not null,
  orden                       integer not null default 0,
  tipo                        text not null default 'entrega'::text,
  direccion                   text not null,
  lat                         double precision,
  lng                         double precision,
  estado                      text not null default 'pendiente'::text,
  completada_at               timestamp with time zone,
  created_at                  timestamp with time zone not null default now()
);

-- tarifas_config
create table public.tarifas_config (
  id                          uuid not null default gen_random_uuid(),
  precio_litro_combustible    numeric,
  litros_km_flete_chico       numeric,
  litros_km_camion_mediano    numeric,
  litros_km_camion_grande     numeric,
  extra_fragil                numeric,
  extra_carga_cara            numeric,
  created_at                  timestamp with time zone default now()
);

-- usuarios
create table public.usuarios (
  id                          uuid not null default gen_random_uuid(),
  nombre                      text,
  email                       text,
  password                    text,
  telefono                    text,
  rol                         text,
  acepta_terminos             boolean default false,
  created_at                  timestamp without time zone default now(),
  cuit                        text,
  contacto                    text,
  direccion                   text,
  deposito                    text,
  dni                         text,
  cuit_cuil                   text,
  licencia                    text,
  cnrt_ruta                   text,
  antecedentes                text,
  patente                     text,
  vehiculo                    text,
  capacidad_carga             text,
  seguro_vehiculo             text,
  seguro_carga                text,
  vtv_rto                     text,
  metodo_cobro                text,
  alias_cbu_cvu               text,
  titular_cuenta              text,
  banco_billetera             text,
  estado_validacion           text default 'pendiente'::text,
  online                      boolean default false,
  zona_operativa              text,
  estado_aprobacion           text default 'pendiente'::text,
  eliminado                   boolean default false,
  bateria_nivel               numeric,
  bateria_cargando            boolean,
  ultima_senal_at             timestamp with time zone,
  categoria_legal             text,
  tipo_vehiculo               text,
  tipo_carroceria             text,
  navegador_preferido         text,
  vehiculo_activo_id          bigint,
  fecha_aceptacion_terminos   timestamp with time zone,
  estado_doc                  text not null default 'pendiente_actualizacion'::text
);

-- vehiculos
create table public.vehiculos (
  id                          bigint not null default nextval('vehiculos_id_seq'::regclass),
  chofer_id                   uuid not null,
  marca                       text not null,
  modelo                      text not null,
  anio                        integer,
  patente                     text not null,
  color                       text,
  tipo_vehiculo               text not null,
  capacidad_kg                integer,
  cedula_verde_url            text,
  seguro_url                  text,
  seguro_vencimiento          date,
  vtv_rto_url                 text,
  vtv_rto_vencimiento         date,
  foto_vehiculo_url           text,
  estado_validacion           text not null default 'pendiente'::text,
  motivo_rechazo              text,
  activo                      boolean not null default false,
  created_at                  timestamp with time zone not null default now(),
  updated_at                  timestamp with time zone not null default now()
);

-- viaje_evidencias
create table public.viaje_evidencias (
  id                          bigint not null default nextval('viaje_evidencias_id_seq'::regclass),
  carga_id                    bigint not null,
  usuario_id                  uuid,
  rol_usuario                 text,
  evento                      text not null,
  estado_viaje                text,
  lat                         numeric,
  lng                         numeric,
  nombre_receptor             text,
  observacion                 text,
  foto_url                    text,
  created_at                  timestamp with time zone default now(),
  tipo_operacion              text,
  tipo_carga                  text,
  entrego_nombre              text,
  recibio_nombre              text,
  parada_id                   bigint
);

-- Propiedad de las secuencias (equivale al bigserial de producción).
alter sequence public.consentimientos_legales_id_seq owned by public.consentimientos_legales.id;
alter sequence public.paradas_viaje_id_seq owned by public.paradas_viaje.id;
alter sequence public.vehiculos_id_seq owned by public.vehiculos.id;
alter sequence public.viaje_evidencias_id_seq owned by public.viaje_evidencias.id;

commit;
