// Tests LOCALES de secuencias.mjs, de docs/staging/sql/09-secuencias-seed.sql y de su integración en aplicar.mjs.
// Sin red, sin Supabase, sin Postgres, sin claves: el SQL se comprueba con verificaciones estáticas y con la implementación de referencia calcularSetval().
// Ejecutar: node --test scripts/staging/seed/secuencias.test.mjs
import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import * as S from "./secuencias.mjs";
import * as D from "./datos.mjs";

const AQUI = dirname(fileURLToPath(import.meta.url));
const SQL01 = readFileSync(resolve(AQUI, "../../../docs/staging/sql/01-schema.sql"), "utf8");
const SQL09 = readFileSync(resolve(AQUI, "../../../docs/staging/sql/09-secuencias-seed.sql"), "utf8");
const APLICAR = readFileSync(resolve(AQUI, "aplicar.mjs"), "utf8");
const SECUENCIAS_MOD = readFileSync(resolve(AQUI, "secuencias.mjs"), "utf8");
const BASE = "https://abcdefghij0123456789.supabase.co";
const AFECTADAS = ["cargas", "consentimientos_legales", "paradas_viaje", "vehiculos", "viaje_evidencias"];
const UUID = ["billetera_chofer", "documentacion_chofer", "mensajes_viaje", "usuarios"];
const sinComentarios = (t) => t.split("\n").filter((l) => !/^\s*(--|\/\/|\*|\/\*\*)/.test(l)).join("\n");

// ═══════════════ 1. Qué tablas del seed usan secuencia ═══════════════
test("el seed inserta ids NUMÉRICOS explícitos solo en 5 tablas; las otras 4 usan uuid; tarifas_config no recibe filas", () => {
  const r = S.idsNumericosDelSeed(D, BASE);
  assert.deepEqual(Object.keys(r.numericas).sort(), AFECTADAS); assert.deepEqual([...r.uuid].sort(), UUID); assert.deepEqual(r.sinId, []);
  assert.deepEqual(r.numericas.cargas, { n: 7, min: 101, max: 107 }); assert.deepEqual(r.numericas.vehiculos, { n: 3, min: 5001, max: 5003 });
  assert.deepEqual(r.numericas.paradas_viaje, { n: 5, min: 1, max: 5 }); assert.deepEqual(r.numericas.viaje_evidencias, { n: 3, min: 1, max: 3 }); assert.deepEqual(r.numericas.consentimientos_legales, { n: 15, min: 1, max: 15 });
});
test("el esquema real (01-schema.sql) asocia secuencia SOLO a esas 5 tablas: 4 serial + cargas identity; todas bigint", () => {
  const e = S.secuenciasEnEsquema(SQL01);
  assert.deepEqual(Object.keys(e).sort(), AFECTADAS);
  for (const t of AFECTADAS) { assert.equal(e[t].tipo, "bigint", t); assert.equal(e[t].secuencia, `${t}_id_seq`, t); }
  assert.equal(e.cargas.mecanismo, "identity"); for (const t of AFECTADAS.filter((x) => x !== "cargas")) assert.equal(e[t].mecanismo, "serial", t);
  for (const t of UUID) assert.ok(!(t in e), `${t} es uuid: no debe tener secuencia`);
  assert.ok(!("tarifas_config" in e));
});
test("NO hay lista escrita a mano: lo que deriva del seed coincide EXACTAMENTE con lo que el esquema declara (si alguien agrega una tabla con secuencia y ids explícitos, este test falla)", () => {
  const delSeed = Object.keys(S.idsNumericosDelSeed(D, BASE).numericas).sort(), delEsquema = Object.keys(S.secuenciasEnEsquema(SQL01)).sort();
  assert.deepEqual(delSeed, delEsquema);
});
test("las columnas id de uuid usan gen_random_uuid() (no necesitan secuencia)", () => {
  for (const t of UUID.concat(["tarifas_config"])) { const m = new RegExp(`create table public\\.${t} \\([\\s\\S]*?\\n\\);`).exec(SQL01); assert.ok(m, t); assert.match(m[0], /\n\s*id\s+uuid not null default gen_random_uuid\(\)/, t); }
});
test("todas las secuencias del esquema empiezan en 1, incrementan de a 1 y tienen cache 1 (supuestos de la regla setval)", () => {
  const seqs = [...SQL01.matchAll(/create sequence public\.(\w+) as (\w+) increment by (\d+) minvalue (\d+) .* start with (\d+) cache (\d+) no cycle;/g)];
  assert.equal(seqs.length, 4); for (const [, , tipo, inc, min, start, cache] of seqs) { assert.equal(tipo, "bigint"); assert.equal(inc, "1"); assert.equal(min, "1"); assert.equal(start, "1"); assert.equal(cache, "1"); }
  assert.match(SQL01, /cargas[\s\S]*?id\s+bigint generated by default as identity/); // identity: incremento 1 por defecto
  for (const m of SQL01.matchAll(/alter sequence public\.(\w+) owned by public\.(\w+)\.id;/g)) assert.equal(m[1], `${m[2]}_id_seq`);
});
test("análisis: por tabla afectada → columna id, tipo, secuencia, ids del seed y mínimo tras el seed", () => {
  const a = S.analizarSecuencias(D, BASE, SQL01);
  assert.deepEqual(a.afectadas.map((x) => [x.tabla, x.columna, x.tipo, x.secuencia, x.idsSeed.min, x.idsSeed.max, x.minimoTrasSeed]).sort((x, y) => x[0].localeCompare(y[0])), [
    ["cargas", "id", "bigint", "cargas_id_seq", 101, 107, 107], ["consentimientos_legales", "id", "bigint", "consentimientos_legales_id_seq", 1, 15, 15],
    ["paradas_viaje", "id", "bigint", "paradas_viaje_id_seq", 1, 5, 5], ["vehiculos", "id", "bigint", "vehiculos_id_seq", 5001, 5003, 5003], ["viaje_evidencias", "id", "bigint", "viaje_evidencias_id_seq", 1, 3, 3]]);
  assert.deepEqual([...a.uuid].sort(), UUID); assert.deepEqual(a.conSecuenciaSinIdsEnSeed, []);
});
test("análisis sin esquema (uso en aplicar.mjs) usa la convención <tabla>_id_seq, que coincide con el esquema real", () => {
  const con = S.analizarSecuencias(D, BASE, SQL01).afectadas.map((x) => [x.tabla, x.secuencia]), sin = S.analizarSecuencias(D, BASE).afectadas.map((x) => [x.tabla, x.secuencia]);
  assert.deepEqual(sin, con);
});
test("el análisis LANZA si el seed inserta ids numéricos en una tabla sin secuencia (inconsistencia)", () => {
  const sql = SQL01.replace("default nextval('paradas_viaje_id_seq'::regclass)", "not null");
  assert.throws(() => S.analizarSecuencias(D, BASE, sql), /paradas_viaje/);
});

// ═══════════════ 2. Regla de setval (referencia del SQL) ═══════════════
test("calcularSetval: secuencia nueva + MAX(id) → avanza a MAX; el siguiente valor es MAX+1", () => {
  assert.deepEqual(S.calcularSetval({ maxId: 5, lastValue: 1, isCalled: false }), { accion: "setval", objetivo: 5, siguiente: 6 });
  assert.deepEqual(S.calcularSetval({ maxId: 107, lastValue: 1, isCalled: false }), { accion: "setval", objetivo: 107, siguiente: 108 });
  assert.deepEqual(S.calcularSetval({ maxId: 5003, lastValue: 1, isCalled: false }), { accion: "setval", objetivo: 5003, siguiente: 5004 });
});
test("calcularSetval: tabla vacía → no toca la secuencia (el primer id sigue siendo 1, no se salta ninguno)", () => {
  assert.deepEqual(S.calcularSetval({ maxId: null, lastValue: 1, isCalled: false }), { accion: "nada", objetivo: 0, siguiente: 1 });
  assert.deepEqual(S.calcularSetval({ maxId: 0, lastValue: 1, isCalled: false }).accion, "nada");
});
test("calcularSetval: NUNCA retrocede (secuencia ya por encima de MAX(id), p. ej. tras pruebas que borraron filas)", () => {
  assert.deepEqual(S.calcularSetval({ maxId: 5, lastValue: 50, isCalled: true }), { accion: "nada", objetivo: 50, siguiente: 51 });
  assert.equal(S.calcularSetval({ maxId: 5, lastValue: 6, isCalled: false }).accion, "nada"); // efectivo 5 = MAX: ya alineada
});
test("calcularSetval es IDEMPOTENTE y funciona al REAPLICAR el seed: correrla dos veces = una; tras crear filas nuevas vuelve a avanzar solo lo necesario", () => {
  let est = { lastValue: 1, isCalled: false };
  const correr = (maxId) => { const r = S.calcularSetval({ maxId, ...est }); if (r.accion === "setval") est = { lastValue: r.objetivo, isCalled: true }; return r; };
  assert.equal(correr(5).accion, "setval"); assert.equal(correr(5).accion, "nada"); assert.equal(correr(5).accion, "nada"); // aplicar seed → 09 → 09 otra vez
  const a1 = S.calcularSetval({ maxId: 5, ...est }); assert.equal(a1.siguiente, 6);
  est = { lastValue: 8, isCalled: true }; assert.equal(correr(5).accion, "nada"); // el seed se reaplica (upsert de ids 1..5) y las pruebas ya habían consumido 6–8
  assert.equal(correr(60).accion, "setval"); assert.equal(est.lastValue, 60); // alguien insertó explícitamente un id alto
});
test("simulación completa con las 5 tablas: el próximo id de cada secuencia queda libre (> MAX(id)) y ningún INSERT sin id choca con el seed", () => {
  const { numericas } = S.idsNumericosDelSeed(D, BASE);
  for (const [t, s] of Object.entries(numericas)) {
    let est = { lastValue: 1, isCalled: false };
    // ANTES: el próximo id (1) choca con el seed si min ≤ 1
    const proximoAntes = est.isCalled ? est.lastValue + 1 : est.lastValue;
    const chocaAntes = proximoAntes >= s.min && proximoAntes <= s.max;
    const r = S.calcularSetval({ maxId: s.max, ...est }); est = { lastValue: r.objetivo, isCalled: true };
    assert.ok(est.lastValue + 1 > s.max, t);
    if (["paradas_viaje", "viaje_evidencias", "consentimientos_legales"].includes(t)) assert.equal(chocaAntes, true, `${t}: sin el paso, el primer INSERT sin id chocaría`);
  }
});

// ═══════════════ 3. Lectura de MAX(id) real (solo lectura) ═══════════════
function sbFalso(tablas, { errorEn = null } = {}) {
  const llamadas = [];
  return { llamadas, from: (t) => { const q = { t, ops: [] }; llamadas.push(q); const ch = { select: (c) => { q.ops.push(["select", c]); return ch; }, order: (c, o) => { q.ops.push(["order", c, o]); return ch; }, limit: (n) => { q.ops.push(["limit", n]); return ch; },
    then: (res, rej) => Promise.resolve(t === errorEn ? { data: null, error: { message: "boom" } } : { data: (tablas[t] ?? []).slice().sort((a, b) => b.id - a.id).slice(0, 1), error: null }).then(res, rej) }; return ch; } };
}
test("maximosReales lee MAX(id) por REST con select/order desc/limit 1; tabla vacía → null; error → se informa sin lanzar; nunca escribe", async () => {
  const sb = sbFalso({ paradas_viaje: [{ id: 3 }, { id: 9 }, { id: 5 }], cargas: [] }, { errorEn: "vehiculos" });
  const r = await S.maximosReales(sb, ["paradas_viaje", "cargas", "vehiculos"]);
  assert.deepEqual(r, { paradas_viaje: { max: 9 }, cargas: { max: null }, vehiculos: { error: "boom" } });
  for (const q of sb.llamadas) assert.deepEqual(q.ops.map((o) => o[0]), ["select", "order", "limit"]);
});
test("informe posterior al seed: MAX(id) real por tabla, mínimo que debe tener la secuencia (el mayor entre seed y real) y el paso manual; sin números escritos a mano", () => {
  const a = S.analizarSecuencias(D, BASE);
  const l = S.lineasPasoSecuencias(a, { cargas: { max: 107 }, consentimientos_legales: { max: 15 }, paradas_viaje: { max: 42 }, vehiculos: { max: null }, viaje_evidencias: { error: "boom" } }).join("\n");
  assert.match(l, /PASO MANUAL OBLIGATORIO/); assert.match(l, /09-secuencias-seed\.sql/); assert.match(l, /paradas_viaje_id_seq\s+MAX\(id\) real = 42 → la secuencia debe quedar ≥ 42/);
  assert.match(l, /cargas_id_seq\s+MAX\(id\) real = 107 → la secuencia debe quedar ≥ 107/); assert.match(l, /vehiculos_id_seq\s+MAX\(id\) real = \(vacía\) → la secuencia debe quedar ≥ 5003/);
  assert.match(l, /viaje_evidencias_id_seq\s+no se pudo leer MAX\(id\) \(boom\)/); assert.match(l, /23505/);
});
test("informe del dry-run: las 5 tablas con su mínimo y las tablas uuid que no necesitan nada; sin conexión", () => {
  const l = S.lineasSecuenciasDryRun(S.analizarSecuencias(D, BASE)).join("\n");
  for (const t of AFECTADAS) assert.match(l, new RegExp(`${t}\\s+${t}_id_seq`)); for (const t of UUID) assert.ok(l.includes(t));
  assert.match(l, /cargas_id_seq\s+ids seed 101…107 → la secuencia debe quedar ≥ 107/);
});

// ═══════════════ 4. El SQL 09 (verificaciones estáticas) ═══════════════
const SQL09_CODIGO = sinComentarios(SQL09);
const BLOQUE = /\$alinear\$([\s\S]*?)\$alinear\$/.exec(SQL09_CODIGO)[1];
test("09: solo staging (misma guarda que 05: aborta si existen las backup_*_20260614 de producción) y la guarda va ANTES de tocar nada", () => {
  assert.match(SQL09_CODIGO, /to_regclass\('public\.backup_usuarios_20260614'\) is not null[\s\S]*?to_regclass\('public\.backup_cargas_20260614'\) is not null[\s\S]*?raise exception 'ABORTADO/);
  assert.ok(SQL09_CODIGO.indexOf("$guarda$") < SQL09_CODIGO.indexOf("setval"));
});
test("09: el único efecto es setval sobre secuencias; nada de DDL, borrados, inserts, updates, truncates ni grants", () => {
  assert.ok(!/\b(truncate|delete|drop|insert|update|alter|create|grant|revoke|copy|vacuum)\b/i.test(SQL09_CODIGO.replace(/'[^']*'/g, "''")), "solo lectura + setval");
  assert.equal((SQL09_CODIGO.match(/setval\(/g) ?? []).length, 1); assert.match(SQL09_CODIGO, /perform setval\(s, mx, true\)/);
});
test("09: sin números mágicos ni nombres de tabla escritos a mano; la secuencia se descubre con pg_get_serial_sequence y el valor sale de MAX(id) real", () => {
  assert.ok(!/setval\([^)]*\d/.test(BLOQUE), "ningún literal numérico en setval");
  for (const t of AFECTADAS.concat(UUID)) assert.ok(!BLOQUE.includes(t), `el bloque no debe nombrar ${t}`);
  assert.match(BLOQUE, /pg_get_serial_sequence\(format\('public\.%I', t\), 'id'\)/); assert.match(BLOQUE, /select coalesce\(max\(id\), 0\) from public\.%I/); assert.match(BLOQUE, /information_schema\.columns/);
});
test("09: nunca retrocede e implementa la MISMA regla que calcularSetval (efectivo = is_called ? last : last-1; setval solo si MAX(id) > efectivo)", () => {
  assert.match(BLOQUE, /efect := case when llamada then ult else ult - 1 end/); assert.match(BLOQUE, /if mx > efect then/); assert.match(BLOQUE, /continue when s is null/);
  assert.match(BLOQUE, /select last_value, is_called from %s/);
});
test("09: transacción explícita (begin … commit), search_path fijo y verificación final de solo lectura con columna estado (PASS/FAIL)", () => {
  assert.match(SQL09_CODIGO, /^\s*begin;/); assert.match(SQL09_CODIGO, /set local search_path to public, extensions;/); assert.match(SQL09_CODIGO, /commit;/);
  const final = SQL09_CODIGO.slice(SQL09_CODIGO.indexOf("commit;")); assert.match(final, /from pg_sequences s/); assert.match(final, /then 'PASS' else 'FAIL' end\s+as estado/); assert.ok(!/setval|update|insert|delete/i.test(final));
});
test("09: aclara que NO es generado ni verificado por el generador (01–08) y cuándo ejecutarlo", () => {
  assert.match(SQL09, /NO lo genera generar-esquema\.mjs ni lo cubre verificar-sql-staging\.mjs/); assert.match(SQL09, /DESPUÉS de `seed\/aplicar\.mjs --aplicar`/); assert.match(SQL09, /IDEMPOTENTE/);
});

// ═══════════════ 5. Integración en aplicar.mjs ═══════════════
test("aplicar.mjs: el aviso de secuencias va DESPUÉS de las guardas (URL/ref/--confirmar) y el paso posterior DESPUÉS del último upsert y de crear el cliente", () => {
  const i = (s) => APLICAR.indexOf(s);
  assert.ok(i("asegurarNoProduccion(url") > 0 && i("flag(\"confirmar\") !== host") > 0);
  assert.ok(i("lineasSecuenciasDryRun(") > i("flag(\"confirmar\") !== host") && i("lineasSecuenciasDryRun(") < i("if (!aplicar)"), "el dry-run informa sin conectar y ya pasó las guardas");
  assert.ok(i("createClient(url, clave") < i("maximosReales(sb"), "la lectura de MAX(id) usa el cliente ya creado, después de las guardas y del --aplicar");
  assert.ok(i("maximosReales(sb") > i('await up("consentimientos_legales"'), "después del ÚLTIMO upsert");
  assert.ok(i("SEED APLICADO (falta el paso manual de secuencias") > i("maximosReales(sb"));
});
test("aplicar.mjs sigue siendo REST-only: no ejecuta SQL, no llama setval ni rpc, no importa pg/postgres, y solo suma los imports de ./secuencias.mjs y ../smoke/v3-anon.mjs (redactar)", () => {
  const codigo = sinComentarios(APLICAR);
  assert.ok(!/setval|\.rpc\(|from "pg"|from "postgres"|postgres:\/\/|DATABASE_URL|STAGING_DB/i.test(codigo));
  const imports = [...APLICAR.matchAll(/^import .* from "([^"]+)"/gm)].map((m) => m[1]).sort();
  assert.deepEqual(imports, ["../guardas.mjs", "../smoke/v3-anon.mjs", "./datos.mjs", "./png.mjs", "./secuencias.mjs", "@supabase/supabase-js", "bcryptjs", "node:fs"].sort());
});
test("secuencias.mjs es puro respecto de la base: sin cliente propio, sin red, sin escrituras, sin SQL", () => {
  const codigo = sinComentarios(SECUENCIAS_MOD);
  assert.ok(!/createClient|fetch\(|\.insert\(|\.update\(|\.delete\(|\.upsert\(|\.rpc\(|process\.env|readFile|writeFile/i.test(codigo));
  assert.ok(!/\bsetval\(/.test(codigo), "no ejecuta setval (solo lo nombra en textos)");
  assert.ok(!/^import /m.test(SECUENCIAS_MOD), "sin imports: recibe D y sb por parámetro");
});
